# Generated by Django 4.2.10 on 2025-08-05 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='type',
            new_name='proj_type',
        ),
    ]
