# Generated by Django 4.2.10 on 2025-08-05 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_type_project_proj_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='screenshot',
            new_name='tablet_view',
        ),
    ]
