# Generated by Django 5.1.5 on 2025-01-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_project_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='details',
            field=models.TextField(),
        ),
    ]
