# Generated by Django 5.1.5 on 2025-01-17 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_project_tools_project_outcome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='challenges_and_solutions',
        ),
    ]
