# Generated by Django 5.1.5 on 2025-01-17 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_project_challenges_and_solutions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KeyFeatures',
            new_name='KeyFeature',
        ),
    ]
