# Generated by Django 4.2.10 on 2025-02-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=100)),
                ('page', models.CharField(max_length=100)),
                ('pic1', models.ImageField(blank=True, null=True, upload_to='projectImages')),
                ('pic2', models.ImageField(blank=True, null=True, upload_to='projectImages')),
                ('pic3', models.ImageField(blank=True, null=True, upload_to='projectImages')),
                ('pic4', models.ImageField(blank=True, null=True, upload_to='projectImages')),
                ('pic5', models.ImageField(blank=True, null=True, upload_to='projectImages')),
                ('pic6', models.ImageField(blank=True, null=True, upload_to='projectImages')),
                ('pic7', models.ImageField(blank=True, null=True, upload_to='projectImages')),
                ('pic8', models.ImageField(blank=True, null=True, upload_to='projectImages')),
                ('pic9', models.ImageField(blank=True, null=True, upload_to='projectImages')),
                ('pic10', models.ImageField(blank=True, null=True, upload_to='projectImages')),
                ('text1', models.TextField(blank=True, null=True)),
                ('text2', models.TextField(blank=True, null=True)),
                ('text3', models.TextField(blank=True, null=True)),
                ('text4', models.TextField(blank=True, null=True)),
                ('text5', models.TextField(blank=True, null=True)),
                ('text6', models.TextField(blank=True, null=True)),
                ('text7', models.TextField(blank=True, null=True)),
                ('text8', models.TextField(blank=True, null=True)),
                ('text9', models.TextField(blank=True, null=True)),
                ('text10', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
