# Generated by Django 5.1.5 on 2025-02-06 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagedata',
            name='pic1',
        ),
        migrations.RemoveField(
            model_name='pagedata',
            name='pic10',
        ),
        migrations.RemoveField(
            model_name='pagedata',
            name='pic2',
        ),
        migrations.RemoveField(
            model_name='pagedata',
            name='pic3',
        ),
        migrations.RemoveField(
            model_name='pagedata',
            name='pic4',
        ),
        migrations.RemoveField(
            model_name='pagedata',
            name='pic5',
        ),
        migrations.RemoveField(
            model_name='pagedata',
            name='pic6',
        ),
        migrations.RemoveField(
            model_name='pagedata',
            name='pic7',
        ),
        migrations.RemoveField(
            model_name='pagedata',
            name='pic8',
        ),
        migrations.RemoveField(
            model_name='pagedata',
            name='pic9',
        ),
        migrations.RemoveField(
            model_name='pagedata',
            name='text1',
        ),
        migrations.RemoveField(
            model_name='pagedata',
            name='text10',
        ),
        migrations.RemoveField(
            model_name='pagedata',
            name='text2',
        ),
        migrations.RemoveField(
            model_name='pagedata',
            name='text3',
        ),
        migrations.RemoveField(
            model_name='pagedata',
            name='text4',
        ),
        migrations.RemoveField(
            model_name='pagedata',
            name='text5',
        ),
        migrations.RemoveField(
            model_name='pagedata',
            name='text6',
        ),
        migrations.RemoveField(
            model_name='pagedata',
            name='text7',
        ),
        migrations.RemoveField(
            model_name='pagedata',
            name='text8',
        ),
        migrations.RemoveField(
            model_name='pagedata',
            name='text9',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projectImages')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designs.pagedata')),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designs.pagedata')),
            ],
        ),
    ]
