# Generated by Django 5.1.5 on 2025-02-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0005_remove_pagedata_screenshot_pagedata_screenshotlaptop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='file'),
        ),
    ]
